version: '3.9'
services:
  # mongodb
  mongodb:
    image: mongo:latest
    restart: always
    env_file: ./.env
    ports:
      - 12346:27017
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  # node app    
  my-node-app:
    build: .
    env_file: ./.env
    ports:
      - "4000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:12346
      DB_USER: $MONGODB_USER
      DB_PASSWORD: $MONGODB_PASSWORD
      DB_PORT: $MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

volumes:
  mongodb: {}